// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/blog/blog.proto

package blog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogPost struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PostId          string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`                            // Unique identifier for the post
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                            // Title of the blog post
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                        // Content of the blog post
	Author          string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`                                          // Author of the blog post
	PublicationDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=publication_date,json=publicationDate,proto3" json:"publication_date,omitempty"` // Publication date of the blog post
	UpdatedDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`             // Creation date of the blog post
	Tags            []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                                              // Tags associated with the blog post
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlogPost) Reset() {
	*x = BlogPost{}
	mi := &file_proto_blog_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPost) ProtoMessage() {}

func (x *BlogPost) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPost.ProtoReflect.Descriptor instead.
func (*BlogPost) Descriptor() ([]byte, []int) {
	return file_proto_blog_blog_proto_rawDescGZIP(), []int{0}
}

func (x *BlogPost) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *BlogPost) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BlogPost) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BlogPost) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BlogPost) GetPublicationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PublicationDate
	}
	return nil
}

func (x *BlogPost) GetUpdatedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedDate
	}
	return nil
}

func (x *BlogPost) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Request message for creating a new blog post
// Input: Post details (Title, Content, Author, Publication Date, Tags)
// Publication Date is optional and defaults to the current time if not provided
type CreateBlogPostRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                                  // Title of the blog post
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                              // Content of the blog post
	Author          string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`                                                // Author of the blog post
	PublicationDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=publication_date,json=publicationDate,proto3,oneof" json:"publication_date,omitempty"` // Publication date of the blog post (optional)
	Tags            []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                                                    // Tags associated with the blog post
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBlogPostRequest) Reset() {
	*x = CreateBlogPostRequest{}
	mi := &file_proto_blog_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogPostRequest) ProtoMessage() {}

func (x *CreateBlogPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogPostRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_blog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBlogPostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateBlogPostRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateBlogPostRequest) GetPublicationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PublicationDate
	}
	return nil
}

func (x *CreateBlogPostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Response message for creating a new blog post
// Output: The Post (PostID, Title, Content, Author, Publication Date, Tags)
type CreateBlogPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *BlogPost              `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"` // The created blog post
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogPostResponse) Reset() {
	*x = CreateBlogPostResponse{}
	mi := &file_proto_blog_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogPostResponse) ProtoMessage() {}

func (x *CreateBlogPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogPostResponse.ProtoReflect.Descriptor instead.
func (*CreateBlogPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_blog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBlogPostResponse) GetPost() *BlogPost {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *CreateBlogPostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBlogPostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for retrieving a blog post
// Input: PostID of the post to retrieve
type GetBlogPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"` // Unique identifier for the post to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogPostRequest) Reset() {
	*x = GetBlogPostRequest{}
	mi := &file_proto_blog_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogPostRequest) ProtoMessage() {}

func (x *GetBlogPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogPostRequest.ProtoReflect.Descriptor instead.
func (*GetBlogPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_blog_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlogPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// Response message for retrieving a blog post
// Output: The Post (PostID, Title, Content, Author, Publication Date, Tags)
type GetBlogPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *BlogPost              `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"` // The retrieved blog post
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogPostResponse) Reset() {
	*x = GetBlogPostResponse{}
	mi := &file_proto_blog_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogPostResponse) ProtoMessage() {}

func (x *GetBlogPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogPostResponse.ProtoReflect.Descriptor instead.
func (*GetBlogPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_blog_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlogPostResponse) GetPost() *BlogPost {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *GetBlogPostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBlogPostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for updating a blog post
// Input: PostID of the post to update and new details (Title, Content, Author, Tags)
type UpdateBlogPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"` // Unique identifier for the post to update
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                 // New title of the blog post
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`             // New content of the blog post
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                   // New tags associated with the blog post
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlogPostRequest) Reset() {
	*x = UpdateBlogPostRequest{}
	mi := &file_proto_blog_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogPostRequest) ProtoMessage() {}

func (x *UpdateBlogPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogPostRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlogPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_blog_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBlogPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdateBlogPostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBlogPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateBlogPostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Response message for updating a blog post
// Output: Post details (PostID, Title, Content, Author, Publication Date, Tags)
type UpdateBlogPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *BlogPost              `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"` // The updated blog post
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlogPostResponse) Reset() {
	*x = UpdateBlogPostResponse{}
	mi := &file_proto_blog_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogPostResponse) ProtoMessage() {}

func (x *UpdateBlogPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogPostResponse.ProtoReflect.Descriptor instead.
func (*UpdateBlogPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_blog_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBlogPostResponse) GetPost() *BlogPost {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *UpdateBlogPostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateBlogPostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for deleting a blog post
// Input: PostID of the post to delete
type DeleteBlogPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"` // Unique identifier for the post to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogPostRequest) Reset() {
	*x = DeleteBlogPostRequest{}
	mi := &file_proto_blog_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogPostRequest) ProtoMessage() {}

func (x *DeleteBlogPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogPostRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_blog_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBlogPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// Response message for deleting a blog post
// Output: Success/Failure message
type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_proto_blog_blog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_blog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_blog_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_blog_blog_proto protoreflect.FileDescriptor

const file_proto_blog_blog_proto_rawDesc = "" +
	"\n" +
	"\x15proto/blog/blog.proto\x12\ablog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\bBlogPost\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12E\n" +
	"\x10publication_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fpublicationDate\x12=\n" +
	"\fupdated_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vupdatedDate\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\xd4\x01\n" +
	"\x15CreateBlogPostRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12J\n" +
	"\x10publication_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0fpublicationDate\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tagsB\x13\n" +
	"\x11_publication_date\"s\n" +
	"\x16CreateBlogPostResponse\x12%\n" +
	"\x04post\x18\x01 \x01(\v2\x11.blog.v1.BlogPostR\x04post\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"-\n" +
	"\x12GetBlogPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"p\n" +
	"\x13GetBlogPostResponse\x12%\n" +
	"\x04post\x18\x01 \x01(\v2\x11.blog.v1.BlogPostR\x04post\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"t\n" +
	"\x15UpdateBlogPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"s\n" +
	"\x16UpdateBlogPostResponse\x12%\n" +
	"\x04post\x18\x01 \x01(\v2\x11.blog.v1.BlogPostR\x04post\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"0\n" +
	"\x15DeleteBlogPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"H\n" +
	"\x12DeletePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xcc\x02\n" +
	"\vBlogService\x12Q\n" +
	"\x0eCreateBlogPost\x12\x1e.blog.v1.CreateBlogPostRequest\x1a\x1f.blog.v1.CreateBlogPostResponse\x12H\n" +
	"\vGetBlogPost\x12\x1b.blog.v1.GetBlogPostRequest\x1a\x1c.blog.v1.GetBlogPostResponse\x12Q\n" +
	"\x0eUpdateBlogPost\x12\x1e.blog.v1.UpdateBlogPostRequest\x1a\x1f.blog.v1.UpdateBlogPostResponse\x12M\n" +
	"\x0eDeleteBlogPost\x12\x1e.blog.v1.DeleteBlogPostRequest\x1a\x1b.blog.v1.DeletePostResponseB*Z(github.com/pandae7/go-blogger/proto/blogb\x06proto3"

var (
	file_proto_blog_blog_proto_rawDescOnce sync.Once
	file_proto_blog_blog_proto_rawDescData []byte
)

func file_proto_blog_blog_proto_rawDescGZIP() []byte {
	file_proto_blog_blog_proto_rawDescOnce.Do(func() {
		file_proto_blog_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blog_blog_proto_rawDesc), len(file_proto_blog_blog_proto_rawDesc)))
	})
	return file_proto_blog_blog_proto_rawDescData
}

var file_proto_blog_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_blog_blog_proto_goTypes = []any{
	(*BlogPost)(nil),               // 0: blog.v1.BlogPost
	(*CreateBlogPostRequest)(nil),  // 1: blog.v1.CreateBlogPostRequest
	(*CreateBlogPostResponse)(nil), // 2: blog.v1.CreateBlogPostResponse
	(*GetBlogPostRequest)(nil),     // 3: blog.v1.GetBlogPostRequest
	(*GetBlogPostResponse)(nil),    // 4: blog.v1.GetBlogPostResponse
	(*UpdateBlogPostRequest)(nil),  // 5: blog.v1.UpdateBlogPostRequest
	(*UpdateBlogPostResponse)(nil), // 6: blog.v1.UpdateBlogPostResponse
	(*DeleteBlogPostRequest)(nil),  // 7: blog.v1.DeleteBlogPostRequest
	(*DeletePostResponse)(nil),     // 8: blog.v1.DeletePostResponse
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_proto_blog_blog_proto_depIdxs = []int32{
	9,  // 0: blog.v1.BlogPost.publication_date:type_name -> google.protobuf.Timestamp
	9,  // 1: blog.v1.BlogPost.updated_date:type_name -> google.protobuf.Timestamp
	9,  // 2: blog.v1.CreateBlogPostRequest.publication_date:type_name -> google.protobuf.Timestamp
	0,  // 3: blog.v1.CreateBlogPostResponse.post:type_name -> blog.v1.BlogPost
	0,  // 4: blog.v1.GetBlogPostResponse.post:type_name -> blog.v1.BlogPost
	0,  // 5: blog.v1.UpdateBlogPostResponse.post:type_name -> blog.v1.BlogPost
	1,  // 6: blog.v1.BlogService.CreateBlogPost:input_type -> blog.v1.CreateBlogPostRequest
	3,  // 7: blog.v1.BlogService.GetBlogPost:input_type -> blog.v1.GetBlogPostRequest
	5,  // 8: blog.v1.BlogService.UpdateBlogPost:input_type -> blog.v1.UpdateBlogPostRequest
	7,  // 9: blog.v1.BlogService.DeleteBlogPost:input_type -> blog.v1.DeleteBlogPostRequest
	2,  // 10: blog.v1.BlogService.CreateBlogPost:output_type -> blog.v1.CreateBlogPostResponse
	4,  // 11: blog.v1.BlogService.GetBlogPost:output_type -> blog.v1.GetBlogPostResponse
	6,  // 12: blog.v1.BlogService.UpdateBlogPost:output_type -> blog.v1.UpdateBlogPostResponse
	8,  // 13: blog.v1.BlogService.DeleteBlogPost:output_type -> blog.v1.DeletePostResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_blog_blog_proto_init() }
func file_proto_blog_blog_proto_init() {
	if File_proto_blog_blog_proto != nil {
		return
	}
	file_proto_blog_blog_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blog_blog_proto_rawDesc), len(file_proto_blog_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_blog_blog_proto_goTypes,
		DependencyIndexes: file_proto_blog_blog_proto_depIdxs,
		MessageInfos:      file_proto_blog_blog_proto_msgTypes,
	}.Build()
	File_proto_blog_blog_proto = out.File
	file_proto_blog_blog_proto_goTypes = nil
	file_proto_blog_blog_proto_depIdxs = nil
}
